                .include "../submodules/beeb/include/beeb.s65"

;-------------------------------------------------------------------------

*=$70
fdload_zp:
                .dsection fdload_zp
                .cerror *>$90

;-------------------------------------------------------------------------

*=$2800
                .dsection test_stuff
                .dsection fdload_init_code
                .dsection fdload_working_code
fdload_toc:
                .binary "../build/test_disk/intermediates/toc.dat"
                .cerror *>$3000

;-------------------------------------------------------------------------

                .section test_stuff
                
                jmp fdload.init        ; +0
                jmp fdload.restore     ; +3
                jmp fdload.seek        ; +6
                jmp fdload.read        ; +9
                lda #0          ; +12 (now redundant)
                rts
                jmp test_load_uncompressed_file   ; +15 $0f
                lda #fdload_zp    ; +18
                rts
                lda #fdload.ZX0_src   ; +21 $15
                rts
                lda #fdload.ZX0_dst   ; +24 $18
                rts
                jmp test_full_decomp ; +27 $1b
                jmp fdload.full_decomp      ; +30 $1e
                jmp get_zx02_workspace ; +33 $21
                jmp test_load_compressed_file ; +36 $24

test_load_uncompressed_file: .block
                sta $ffff
                stx load_addr+0
                sty load_addr+1
                sta file_index
                jsr fdload.load_file_disk_data
load_addr:
                .word $3000
file_index: .byte 0
                sta $fffe
                rts
                .endblock

test_load_compressed_file: .block
                sta $ffff
                stx lda_byte+1
                sty lda_byte+2
                ldx #3
loop:
lda_byte: lda $ffff,x
                sta args,x
                dex
                bpl loop
                jsr fdload.load_file_contents
args: .fill 4
                sta $fffe
                rts
                .endblock

test_full_decomp:
                lsr fdload.ZX0_resume_state
                jmp fdload.full_decomp

get_zx02_workspace:
                ldx #<fdload.zx02_workspace
                ldy #>fdload.zx02_workspace
                rts
                
                .endsection

;-------------------------------------------------------------------------

                .include "fdload.s65"
                